# Generated by Django 4.0.4 on 2022-07-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database1',
            name='roll',
            field=models.IntegerField(unique=True),
        ),
    ]
